apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.webhook.pusher: |
    url: %slack_url%
    headers:
      - name: Content-Type
        value: application/json
  service.telegram: |
    token: ''
  context: |
    argocdUrl: %argocdUrl%
  template.app-sync-change: |
    webhook:
      pusher:
        method: POST
        body: |
          {
            "attachments": [
              {
                "title": "ArgoCD 同步完成",
                "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true",
                "color": "#18be52",
                "fields": [
                  {
                    "title": "名稱",
                    "value": "{{.app.metadata.name}}",
                    "short": false,
                  },
                  {
                    "title": "Repository",
                    "value": "{{.app.spec.source.repoURL}}",
                    "short": true,
                  },
                  {
                    "title": "Revision",
                    "value": "{{.app.status.sync.revision}}",
                    "short": true,
                  },
                  {
                    "title": "Image",
                    "value": "{{index .app.status.summary.images 0}}",
                    "short": false,
                  },
                  {
                    "title": "Version",
                    "value": "{{ (split ":" (index .app.status.summary.images 0))._1 }}",
                    "short": true,
                  },
                  {
                    "title": "app同步狀態",
                    "value": "{{.app.status.operationState.phase}}",
                    "short": true,
                  },
                  {
                    "title": "app服務狀態",
                    "value": "{{.app.status.health.status}}",
                    "short": true,
                  }
                ]
              }
            ]
          }
    telegram:
      message: |
        *ArgoCD 同步完成* ✅
        *名稱:* {{.app.metadata.name}}
        *Repository:* {{.app.spec.source.repoURL}}
        *Revision:* {{.app.status.sync.revision}}
        *Image:* {{index .app.status.summary.images 0}}
        *Version:* {{ (split ":" (index .app.status.summary.images 0))._1 }}
        *同步狀態:* {{.app.status.operationState.phase}}
        *服務狀態:* {{.app.status.health.status}}
        [查看詳情]({{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true)
  template.app-sync-degraded: |
    webhook:
      pusher:
        method: POST
        body: |
          {
            "attachments": [
              {
                "title": "ArgoCD 同步失敗",
                "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true",
                "color": "#18be52",
                "fields": [
                  {
                    "title": "名稱",
                    "value": "{{.app.metadata.name}}",
                    "short": false,
                  },
                  {
                    "title": "app同步狀態",
                    "value": "{{.app.status.operationState.phase}}",
                    "short": true,
                  },
                  {
                    "title": "app服務狀態",
                    "value": "{{.app.status.health.status}}",
                    "short": true,
                  }
                ]
              }
            ]
          }
    telegram:
      message: |
        *ArgoCD 同步失敗* ❌
        *名稱:* {{.app.metadata.name}}
        *同步狀態:* {{.app.status.operationState.phase}}
        *服務狀態:* {{.app.status.health.status}}
        [查看詳情]({{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true)
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      send: [app-sync-change]  # template names
      # trigger condition
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
  trigger.on-health-degraded: |
    - description: Application has degraded
      send: [app-sync-degraded]
      when: app.status.health.status == 'Degraded'
  trigger.on-sync-failed: |
    - description: Application syncing has failed
      send: [app-sync-degraded]  # template names
      when: app.status.operationState.phase in ['Error', 'Failed']
  trigger.on-sync-running: |
    - description: Application is being synced
      send: [app-sync-change]  # template names
      when: app.status.operationState.phase in ['Running']
  trigger.on-sync-status-unknown: |
    - description: Application status is 'Unknown'
      send: [app-sync-degraded]  # template names
      when: app.status.sync.status == 'Unknown'
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send: [app-sync-change]  # template names
      when: app.status.operationState.phase in ['Succeeded']
  subscriptions: |
    - recipients:
      - pusher
      - telegram:<chat_id>
      triggers:
      - app-sync-change
      # - on-sync-succeeded
      - on-deployed
      - on-health-degraded
      - on-sync-failed
      # - on-sync-running
      # - on-sync-status-unknown
      # - on-sync-succeeded