apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
  ## Argo CD Notifications Controller Properties
  # Set the logging level. One of: debug|info|warn|error (default "info")
  notificationscontroller.log.level: "info"
  # Set the logging format. One of: text|json (default "text")
  notificationscontroller.log.format: "json"
  # Enable self-service notifications config. Used in conjunction with apps-in-any-namespace. (default "false")
  notificationscontroller.selfservice.enabled: "true"